name: Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.22'

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: goreleaser/goreleaser-action@v6
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: '~> v2'
          args: release --clean --rm-dist
          workdir: app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # build and push docker image for frontend
      - name: Build and Push Docker Image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF#refs/tags/v}"
          IMAGE_NAME="ghcr.io/shaharia-lab/smarty-pants-frontend:$TAG"
          cd frontend/smarty-pants &&
          docker build -f Dockerfile -t "$IMAGE_NAME" .
          docker push "$IMAGE_NAME"